[default]
BeginString=FIX.4.2
ConnectionType=initiator
StartTime=00:00:00
EndTime=20:00:00
UseDataDictionary=Y
DataDictionary=configuration/fix.xml
ValidateUserDefinedFields=N
FileStorePath=${LogBaseDir}/${LogDate}/store
FileLogPath=${LogBaseDir}/${LogDate}/fixlog
ResetOnLogon=N
ResetOnLogout=N
ResetOnDisconnect=N
HeartBtInt=60
ReconnectInterval=5
MaxLatency=600
CheckLatency=N
FileIncludeMilliseconds=Y
FileIncludeTimeStampForMessages=Y
[session]
SocketConnectHost=127.0.0.1
SocketConnectPort=9103
SenderCompID=OM-SEND
TargetCompID=ExgSimulator
